require('settings')
require('mappings')
-- require('nightfox-config')
require('nvim-theme')
require('packer-config')
require('nvim-tree-config')
require('lualine-config')
require('barbar-config/mappings')
require('barbar-config/options')
require('mason-config')
require('snippy-config')
require('lspkind-config')
require('treesitter-config')
require('nvim-cmp-config')
require('lsp-config')
require('floaterm-config')
require('tagbar-config')
require('nvim-autopairs-config')
require('nvim-ts-autotag-config')
require('telescope-config')
-- require('null-ls-config')
require('phpfmt-config')
